# Generated by Django 5.1.5 on 2026-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrecord',
            name='model_version',
            field=models.CharField(default='ScanMyMouth-MobileNetV2-v1.0', max_length=50),
        ),
    ]
